# Generated by Django 2.2.7 on 2019-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.CharField(max_length=100)),
                ('postDate', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('nation', models.CharField(max_length=100)),
                ('missDate', models.DateTimeField()),
                ('missArea', models.CharField(max_length=100)),
                ('physicalPoint', models.CharField(max_length=100)),
                ('additional', models.CharField(max_length=100)),
            ],
        ),
    ]
