# Generated by Django 2.2.7 on 2019-11-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0002_auto_20191121_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing',
            name='missDate',
            field=models.CharField(max_length=100),
        ),
    ]
