# Generated by Django 2.2.7 on 2019-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing', '0003_auto_20191121_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing',
            name='binary',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
    ]
