# Generated by Django 2.2.7 on 2019-11-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('userPw', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('userPhone', models.IntegerField()),
                ('userInfo', models.CharField(max_length=100)),
                ('userPromotion', models.IntegerField()),
            ],
        ),
    ]
