# Generated by Django 2.2.7 on 2019-11-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPhone',
            field=models.CharField(max_length=10),
        ),
    ]
