# Generated by Django 2.2.7 on 2019-11-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191121_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userInfo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhone',
            field=models.CharField(max_length=20),
        ),
    ]
