# Generated by Django 2.2.7 on 2019-11-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191121_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='binary',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
    ]
